export interface ChallengeAboutContent {
  concept: string;
  history: string;
  importance: string;
  tips?: string;
}

export const challengeAboutData: Record<string, ChallengeAboutContent> = {
  "diário de bordo": {
    concept: "O diário de bordo é uma ferramenta de autodesenvolvimento que permite registrar experiências, reflexões e aprendizados diários, promovendo o autoconhecimento e o crescimento pessoal.",
    history: "O conceito surgiu nos séculos de navegação oceânica, quando marinheiros, como os das expedições portuguesas e espanholas, registravam em diários de bordo todos os detalhes das viagens — desde o percurso seguido até os desafios enfrentados durante a travessia. Esses registros eram importantes não apenas para fins administrativos e de navegação, mas também para construir o conhecimento geográfico e histórico daquele período.",
    importance: "O diário de bordo é importante para o jovem por várias razões:\n\n• **Autoconhecimento**: permite compreender melhor os próprios pensamentos, comportamentos e sentimentos.\n\n• **Desenvolvimento da escrita e da expressão**: aprimora habilidades linguísticas e comunicativas.\n\n• **Reflexão e planejamento**: ajuda a analisar experiências e planejar novas ações com base nelas.\n\n• **Responsabilidade e disciplina**: estimula a constância e o comprometimento com o próprio processo de crescimento.\n\nAssim, o diário de bordo serve como um espelho do desenvolvimento pessoal, promovendo não apenas o registro de atividades, mas também a construção de uma identidade mais consciente e autônoma.",
  },
  "75 hard days": {
    concept: "O 75 Hard é definido pelo próprio criador como um \"programa de transformação mental com benefícios físicos como resultado\". Ele foi pensado para testar e fortalecer a disciplina, a consistência e a força de vontade, por meio de tarefas diárias desafiadoras.",
    history: "Andy Frisella desenvolveu o programa após entrevistar James Lawrence, conhecido como \"Iron Cowboy\", famoso por completar 50 triatlos Ironman consecutivos em 50 dias. Inspirado nessa determinação, Frisella criou o 75 Hard como um método de desenvolver resiliência mental e autodisciplina, conceitos que ele depois registrou em seu livro 75 Hard: A Tactical Guide to Winning the War with Yourself (2019). A prática ganhou força nas redes sociais, especialmente no TikTok, atingindo milhões de participantes pelo mundo.",
    importance: "O desafio 75 Hard tem impacto significativo no desenvolvimento pessoal e emocional, ao cultivar hábitos saudáveis e uma mentalidade voltada para a superação.\n\nEntre os principais benefícios estão:\n\n• **Disciplina e foco**: o cumprimento rigoroso das metas diárias fortalece a capacidade de seguir compromissos de longo prazo.\n\n• **Autoconfiança**: vencer pequenos desafios diários aumenta a sensação de controle e realização pessoal.\n\n• **Melhora física e mental**: a combinação de treino, leitura e boa alimentação promove bem-estar integral.\n\n• **Superação de limites pessoais**: o rigor do programa ajuda a vencer preguiça, procrastinação e falta de propósito.\n\nAssim, o 75 Hard Days é mais do que um desafio físico — é um experimento de autodomínio e transformação mental, cujo valor está em ensinar o indivíduo a manter constância, disciplina e resiliência diante de obstáculos diários.",
    tips: "As regras centrais do desafio incluem:\n\n• Seguir uma dieta escolhida pelo participante, sem álcool nem refeições \"livres\".\n• Beber cerca de 3 litros de água por dia.\n• Realizar dois treinos de pelo menos 45 minutos, sendo um deles obrigatoriamente ao ar livre.\n• Ler 10 páginas de um livro de não ficção (preferencialmente sobre crescimento pessoal).\n• Tirar uma foto diária do progresso físico.\n\nEssas tarefas devem ser mantidas sem interrupções durante 75 dias seguidos, reforçando a ideia de compromisso e constância.",
  },
  "diário da gratidão": {
    concept: "O diário da gratidão é uma prática reflexiva que consiste em registrar, diariamente ou com frequência regular, as coisas pelas quais uma pessoa se sente grata. Essa ferramenta, simples e poderosa, está fundamentada na psicologia positiva e tem efeitos comprovados sobre o bem-estar emocional, mental e social.",
    history: "Embora o hábito de registrar reflexões pessoais seja antigo, o diário da gratidão ganhou destaque na psicologia contemporânea a partir dos estudos de psicólogos como Robert Emmons e Martin Seligman, pioneiros da Psicologia Positiva. A prática surgiu como uma estratégia terapêutica para aumentar o bem-estar subjetivo e reduzir sintomas de estresse e ansiedade. Com o tempo, tornou-se popular globalmente como uma ferramenta acessível de desenvolvimento pessoal e autoconhecimento.",
    importance: "Manter um diário da gratidão traz inúmeros benefícios psicológicos e emocionais:\n\n• **Redução do estresse e da ansiedade**: ao focar em aspectos positivos, o cérebro se afasta de preocupações excessivas e tende a reduzir o nível de cortisol, o hormônio do estresse.\n\n• **Melhora do humor e aumento da felicidade**: a gratidão estimula neurotransmissores ligados ao prazer, como serotonina e dopamina, aumentando a sensação de satisfação e alegria.\n\n• **Fortalecimento das relações interpessoais**: expressar reconhecimento pelas pessoas ao redor promove empatia, confiança e vínculos emocionais mais saudáveis.\n\n• **Melhoria do sono**: escrever antes de dormir direciona o foco para pensamentos positivos e ajuda a relaxar, resultando em um sono mais tranquilo.\n\n• **Autoconhecimento e resiliência**: refletir sobre os motivos de gratidão ajuda o indivíduo a perceber padrões de felicidade e lidar com adversidades com atitude mais otimista e equilibrada.\n\nAssim, o diário da gratidão é uma ferramenta transformadora que incentiva o autocuidado, o equilíbrio emocional e o desenvolvimento de uma mentalidade mais positiva e compassiva, fortalecendo tanto o bem-estar individual quanto os laços sociais.",
    tips: "A escrita pode ser feita de maneira espontânea ou orientada por perguntas, como \"pelo que sou grato hoje?\" ou \"qual foi o melhor momento do meu dia?\".",
  },
  "monk mode": {
    concept: "O desafio Monk Mode (ou \"modo monge\") é uma prática de autodesenvolvimento que propõe um período de isolamento voluntário, foco extremo e disciplina mental, inspirado na rotina de monges tradicionais. O objetivo é eliminar distrações, maximizar a produtividade e promover crescimento pessoal e espiritual.",
    history: "O conceito do Monk Mode surgiu em comunidades de autodesenvolvimento e produtividade na internet, especialmente entre grupos masculinos focados em disciplina e controle de impulsos, como o movimento NoFap, que o utilizava como uma forma de \"limpeza mental e espiritual\". Entretanto, suas raízes filosóficas vêm das práticas monásticas antigas, nas quais monges buscavam aperfeiçoamento espiritual através de isolamento, meditação e autodisciplina. Nos últimos anos, a tendência ganhou popularidade entre empreendedores, executivos e criadores de conteúdo digital, viralizando em plataformas como TikTok e YouTube como uma ferramenta moderna de foco e alta performance.",
    importance: "O desafio Monk Mode é considerado um método eficaz de autotransformação, trazendo benefícios mentais, emocionais e até físicos, quando praticado com equilíbrio.\n\nEntre seus principais impactos na vida do indivíduo estão:\n\n• **Foco e produtividade aumentados**: a eliminação de distrações permite concentrar-se totalmente em metas prioritárias.\n\n• **Clareza mental e emocional**: o isolamento e a introspecção ajudam a reduzir ruídos mentais, promovendo calma e autoconhecimento.\n\n• **Disciplina e autocontrole**: o comprometimento com rotinas fixas reforça hábitos positivos e o domínio sobre impulsos e procrastinação.\n\n• **Redução do estresse e da ansiedade**: ao limitar estímulos digitais e adotar uma rotina estruturada, há melhora significativa do bem-estar mental.\n\nAssim, o desafio Monk Mode representa uma jornada voluntária de autodomínio e clareza interior, uma espécie de \"retiro mental moderno\" que ajuda o indivíduo a reconectar-se consigo mesmo e a construir uma vida mais disciplinada, intencional e equilibrada.",
    tips: "Em termos práticos, o modo monge pode incluir hábitos como acordar cedo, meditar, praticar exercícios físicos, seguir uma alimentação saudável, estudar, e evitar distrações eletrônicas ou atividades superficiais.",
  },
  "dopamina detox": {
    concept: "O dopamina detox, também conhecido como jejum de dopamina, é uma prática que consiste em uma pausa voluntária em atividades que estimulam muito o cérebro com recompensas rápidas — como redes sociais, jogos, mensagens e outras distrações digitais. O objetivo é \"resetar\" o sistema de recompensa cerebral para aumentar o foco, a motivação e a capacidade de realizar tarefas que exigem mais esforço e provocam menor estímulo imediato.",
    history: "O conceito surgiu da observação de que o excesso de estímulos rápidos e frequentes sobrecarrega o sistema de dopamina, o neurotransmissor vinculado à sensação de prazer e motivação. Isso pode gerar vícios comportamentais, dificuldade de concentração e busca constante por gratificação instantânea. Influenciadores e profissionais da área de saúde mental popularizaram o detox como estratégia para reduzir essa sobrecarga.",
    importance: "Ao diminuir a exposição a estímulos superestimulantes, o dopamina detox ajuda o indivíduo a recuperar a capacidade de foco, reduzir a procrastinação, diminuir ansiedade e estresse, melhorar o sono e fortalecer o bem-estar emocional. O cérebro aprende a valorizar pequenas recompensas naturais e atividades mais profundas, promovendo maior equilíbrio mental e produtividade.\n\nPorém, especialistas alertam que o detox não é um \"reset\" literal do cérebro, devendo ser feito com equilíbrio e bom senso para evitar efeitos negativos como apatia ou frustração.\n\nEm resumo, o dopamina detox é uma estratégia para controlar a dependência de estímulos rápidos e recobrar o controle sobre a atenção e a motivação, favorecendo uma vida mais equilibrada e produtiva.",
  },
  "biohacking iniciante": {
    concept: "O desafio de Biohacking iniciante consiste em aplicar pequenas mudanças e estratégias, baseadas na ciência, para otimizar a saúde física, mental e o desempenho diário do indivíduo. Originado do termo \"hacking\" (invadir, modificar), o Biohacking é uma abordagem \"faça você mesmo\" que envolve ajustes no estilo de vida, alimentação, sono, exercícios e uso de tecnologias simples para melhorar o bem-estar.",
    history: "A história do Biohacking é recente e vem da interseção entre a biologia, tecnologia e o desejo de autoaperfeiçoamento. Ele ganhou popularidade com o avanço de monitoramento de dados pessoais (como sono e alimentação) e a busca por vida mais saudável e produtiva.",
    importance: "A importância deste desafio para o indivíduo está na capacidade de tornar consciente e controlada a própria saúde, promovendo maior energia, concentração, melhora no sono, na disposição física e mental, além de prevenir doenças. É uma prática personalizada que estimula a experimentação e o autoconhecimento, possibilitando mudanças eficazes e sustentáveis no estilo de vida.\n\nEm resumo, o desafio de Biohacking iniciante é um caminho para quem deseja melhorar sua qualidade de vida através de pequenos ajustes diários fundamentados na ciência e na experimentação pessoal.",
  },
};

export function getChallengeAbout(challengeName: string): ChallengeAboutContent | null {
  const normalized = challengeName.toLowerCase().trim();
  return challengeAboutData[normalized] || null;
}
