project_id = "jlqntjsxhyyquhfufihd"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.translate-dynamic-content]
verify_jwt = true

